version: '3.9'

services:
  frontend:
    image: frontend:alpha
    container_name: frontend
    restart: unless-stopped
    networks:
      - net
    ports:
      - 3001:80

networks:
  net:
    name: net
    external: true